---
container_name: fairpoints-backend
image_name: "scottg489/fairpoints-backend:{{ lookup('env', '_APP_DOCKER_IMAGE_TAG') }}"
twilio:
  account_sid: "{{ lookup('env', '_TWILIO_ACCOUNT_SID') }}"
  api_key: "{{ lookup('env', '_TWILIO_API_KEY') }}"
  api_secret: "{{ lookup('env', '_TWILIO_API_SECRET') }}"
  chat_service_sid: "{{ lookup('env', '_TWILIO_CHAT_SERVICE_SID') }}"
aws:
  access_key_id: "{{ lookup('env', '_AWS_ACCESS_KEY_ID') }}"
  secret_access_key: "{{ lookup('env', '_AWS_SECRET_ACCESS_KEY') }}"
  dynamodb_table: "{{ lookup('env', '_DYNAMODB_TABLE') }}"
