name: PR CI

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - name: Build and push image which app build runs on
        run: ./infra/build/build.sh ${{ secrets.ID_RSA_CONTENTS_BASE64 }} ${{ secrets.DOCKER_CONFIG_CONTENTS_BASE64 }}
        env:
          GIT_REPO_URL: 'git@github.com:ScottG489/fairpoints-backend.git'
          RELATIVE_SUB_DIR: 'infra/build'

  test_application:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
    - name: Build and test
      run: |
        ./build.sh \
        test \
        ${{ secrets.ID_RSA_CONTENTS_BASE64 }} \
        ${{ secrets.DOCKER_CONFIG_CONTENTS_BASE64 }} \
        ${{ secrets.AWS_CREDENTIALS_CONTENTS_BASE64 }} \
        ${{ secrets.MAINKEYPAIR_CONTENTS_BASE64 }} \
        ${{ secrets.TWILIO_ACCOUNT_SID_BASE64 }} \
        ${{ secrets.TWILIO_API_KEY_BASE64 }} \
        ${{ secrets.TWILIO_API_SECRET_BASE64 }} \
        ${{ secrets.TWILIO_CHAT_SERVICE_SID_BASE64 }} \
        ${{ secrets.AWS_ACCESS_KEY_ID_BASE64 }} \
        ${{ secrets.AWS_SECRET_ACCESS_KEY_BASE64 }}
